# Generated by Django 3.0.4 on 2020-04-01 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_likes'),
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupmember', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.GroupMember')),
                ('posts', models.ManyToManyField(to='post.Post')),
            ],
        ),
    ]
