# Generated by Django 3.0.4 on 2020-04-02 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_grouppost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GroupPost',
        ),
    ]
